version: '3.8'

services:
  nginx:
   image: nginx:latest  
   restart: always
   volumes: 
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - static_volume:/home/where_to_go/static 
     - media_volume:/home/where_to_go/django_media 
   ports: 
     - 8080:80 
   depends_on: 
     - api
  api:
    image: pavel2232/where_to_go:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - .env
    depends_on:
      db:
          condition: service_healthy
    expose:
    - 8000
    volumes:
      - static_volume:/home/where_to_go/static
      - media_volume:/home/where_to_go/django_media
    container_name: where_to_go_app
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pablo -d wheretogo"]
      interval: 5s
      timeout: 30s
      retries: 5
    container_name: pg_db




volumes:
  postgres_data:
  static_volume:
  media_volume:
